version: '3.8'
services:

  app:
    container_name: fsd_app
    depends_on:
      - server
    build:
      context: ./frontend
    ports:
      - 8080:8080

  server:
    depends_on:
      - mongo
    build:
      context: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_CONNECTION=mongodb://mongoadmin:password@fsd_mongodb:27017
   
  mongo:
    container_name: fsd_mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
