ARG NODE_VERSION=20.11.0

FROM --platform=linux/amd64 node:${NODE_VERSION}-alpine

RUN mkdir /app

WORKDIR /app

COPY package*.json .

RUN yarn

COPY . .

EXPOSE 8080

CMD [ "yarn", "dev" ]