version: '3.8'
services:

  api:
    container_name: api
    depends_on:
      - db
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app 
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGODB_CONNECTION=mongodb://mongoadmin:password@db:27017
   
  db:
    container_name: db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
